version: "3.3"
services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    restart: always
    ports:
      - 3002:3001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - .:/app/data