version: '3.3'
services:
  onedev:
    image: 1dev/server
    container_name: onedev
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./onedev:/opt/onedev
    ports:
      - '6610:6610'
      - '6611:6611'