version: "3.3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    ports:
      - 3100:3000
    volumes:
      - .:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro