version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - JELLYFIN_PublishedServerUrl=192.168.1.100
    volumes:
      - ./library:/config
      - ./tvseries:/data/tvshows
      - ./movies:/data/movies
      - ./tv:/data/tv
    ports:
      - 8096:8096
    restart: unless-stopped
